# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clear_mem <- function() {
    invisible(.Call('NBCD_clear_mem', PACKAGE = 'NBCD'))
}

get_mem <- function() {
    .Call('NBCD_get_mem', PACKAGE = 'NBCD')
}

kMcpp <- function(p, p1 = as.numeric( c()), p2 = as.numeric( c()), i1 = as.integer( c()), imem = 0L) {
    .Call('NBCD_kMcpp', PACKAGE = 'NBCD', p, p1, p2, i1, imem)
}

